name: Send gotify notification

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      priority:
        required: true
        type: number
    secrets:
      GOTIFY_URL:
        required: true
      GOTIFY_TOKEN:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Gotify Notification
        run: |
          curl -X POST "${{ secrets.GOTIFY_URL }}/message?token=${{ secrets.GOTIFY_TOKEN }}" \
          -F "title=Docker Deploy Notification" \
          -F "message=${{ inputs.message }}" \
          -F "priority=${{ inputs.priority }}"
